### ISSUE TITLE
Creating a conf file by copying an pasting from help docs does not work

### ISSUE THREAD

**Issue by yhamidi** [intel-hpdd/Online-Help#46]
When creating /tmp/lustre-repo.conf by copy and paste from instructions file: https://intel-hpdd.github.io/Online-Help/docs/Upgrade_Guide/Upgrade_EE-3.1-el7_to_LU-LTS-el7.html, the file format has issues (see below). It only worked in the the line were type in. 

reposync -c /tmp/lustre-repo.conf -n  -r lustre-server  -r lustre-client  -r e2fsprogs-wc
Traceback (most recent call last):
  File "/bin/reposync", line 343, in <module>
    main()
  File "/bin/reposync", line 148, in main
    my.doConfigSetup(fn=opts.config, init_plugins=opts.plugins)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 298, in doConfigSetup
    return self.conf
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1078, in <lambda>
    conf = property(fget=lambda self: self._getConfig(),
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 349, in _getConfig
    startupconf = config.readStartupConfig(fn, root, releasever)
  File "/usr/lib/python2.7/site-packages/yum/config.py", line 1080, in readStartupConfig
    raise Errors.ConfigError("Parsing file failed: %s" % e)
yum.Errors.ConfigError: Parsing file failed: File contains parsing errors: file:///tmp/lustre-repo.conf

**Comment by jgrund** [comment]
@yhamidi can you paste the location of the command that is failing? You've only pasted the table of contents.
